Script started on 2022-10-06 21:07:15-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]777;notify;Command completed;ls\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ echo $SHELL
[?2004l]777;preexec\/bin/bash
]777;notify;Command completed;echo $SHELL\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ whoami
[?2004l]777;preexec\couchcai
]777;notify;Command completed;whoami\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ pwd
[?2004l]777;preexec\/home/couchcai/cse374
]777;notify;Command completed;pwd\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ uname -a
[?2004l]777;preexec\Linux localhost.localdomain 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
]777;notify;Command completed;uname -a\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ gcc --version -std.[K=c11
[?2004l]777;preexec\gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

]777;notify;Command completed;gcc --version -std=c11\]777;precmd\]0;couchcai@localhost:~/cse374\]7;file://localhost/home/couchcai/cse374\[?2004h[couchcai@localhost cse374]$ exit
[?2004l]777;preexec\exit

Script done on 2022-10-06 21:07:47-07:00 [COMMAND_EXIT_CODE="0"]
